from rest_framework.routers import DefaultRouter
from . import api

router = DefaultRouter()
router.register('login', api.UserLoginView, basename='api_login')
router.register('signup', api.UserCreationView, basename='api_sign')
router.register('resend-activation-link', api.UserResendActivationView, basename='api_resend_activation')
router.register('otp-send', api.OtpSendView, basename='api_otp_send')
router.register('forgot-password', api.ForgotPasswordView, basename='api_forgot_password')
router.register('otp-login', api.OtpLoginView, basename='api_otp_login')
router.register('verify-token', api.VerifyTokenView, basename='api_verify_token')
router.register('active-token', api.ActiveTokenView, basename='api_active_token')
router.register('active-account', api.ActiveAccountView, basename='api_active_account')
router.register('change-password', api.ChangePasswordView, basename='api_change_password')
router.register('users', api.UsersViewSet, basename='api_users')
router.register('profile', api.ProfileViewSet, basename='api_profile')
router.register('banner', api.BannerViewSet, basename='api_banner')
router.register('devices', api.FCMDeviceViewSet)
router.register('user-details', api.UserDetailViewSet, basename='api_user_details')
router.register('notifications', api.NotificationsViewSet, basename='api_notifications')
router.register('contact', api.ContactViewSet, basename='api_contact')
router.register('feedback', api.FeedbackViewSet, basename='api_feedback')
router.register('faqs', api.FaqsViewSet, basename='api_faqs')
router.register('check-user', api.AvailabilityViewSet, basename='api_availability')
router.register('bulk-read-notifications', api.BulkNotificationsViewSet, basename='api_bulk_notifications_read')
